### ISSUE TITLE
Add Rust part of the dependency recipes

### ISSUE THREAD

**Issue by neithanmo** [Zondax/meta-zondax#6]
As discussed last Friday. It is good to have Rust part of the recipes so users can modify them according to their needs.

**Comment by keyfour** [comment]
Rust layer is added [here](https://github.com/Zondax/tee-manifest/blob/06c466f175721c014e42141be93ef12204c9bf42/default.xml#L16). And some extra configs required to build it are placed [here](https://github.com/Zondax/meta-zondax/blob/dev/recipes-devtools/rust/rust_%25.bbappend)
